on:
  push:
    branches: ["testing"]

jobs:
  build-exe:
    runs-on: windows-latest
    steps:
      # System depedencies
      - uses: ilammy/msvc-dev-cmd@v1
      - uses: RiskoZoSlovenska/gh-actions-lua-static@static  # See https://github.com/lunarmodules/luasystem/pull/17#issuecomment-1986387525
        with:
          luaVersion: "5.2"
      - uses: luarocks/gh-actions-luarocks@master  # See https://github.com/leafo/gh-actions-luarocks/pull/14
        with:
          luaRocksVersion: "3.11.1"

      - run: tree ".lua" /f /a
      - run: type $env:APPDATA"/luarocks/config-5.1.lua"

      - name: Install luastatic
        run: luarocks install luastatic

      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: pilot-compiler

      - name: Make
        run: luarocks make
        working-directory: pilot-compiler

      - name: Bundle
        run: |
          luastatic pilot-compiler.lua `
            $(lua find-files.lua pilot-compiler --lua) `
            "${{ github.workspace }}/.lua/lib/lua51.lib" `
            $(lua find-files.lua pilot-compiler --bin) `
            -I"${{ github.workspace }}/.lua/include"
        working-directory: pilot-compiler

      - run: tree /f /a
        working-directory: pilot-compiler

      - uses: actions/upload-artifact@v4
        with:
          path: pilot-compiler/pilot-compiler.exe

      - name: Test
        run: ../pilot-compiler.exe main.lua
        working-directory: pilot-compiler/example
