on:
  push:
    branches: ["testing"]

jobs:
  build-exe:
    runs-on: windows-latest
    steps:
      # Install system depedencies
      - uses: ilammy/msvc-dev-cmd@v1
      - uses: leafo/gh-actions-lua@v10
      - uses: hishamhm/gh-actions-luarocks@master  # See https://github.com/leafo/gh-actions-luarocks/pull/14

      - name: Checkout srlua
        uses: actions/checkout@v4
        with:
            repository: LuaDist/srlua
            ref: dd0fc9461b4722d673631245d616e92c7c93c590
            path: srlua

      - name: Checkout pilot-compiler
        uses: actions/checkout@v4

      - name: Build srlua
        run: |
          git apply ../srlua.patch
          make srlua.exe
        working-directory: srlua

      - run: |
          luarocks make
          srlua/glue srlua/srlua.exe pilot-compiler.lua pilot-compiler.exe

      - run: |
          ../pilot-compiler.exe main.lua
        working-directory: example
