on:
  push:
    branches: ["testing"]

jobs:
  build-exe:
    runs-on: windows-latest
    steps:
      # Install system depedencies
      - uses: ilammy/msvc-dev-cmd@v1
      - uses: leafo/gh-actions-lua@v10
        with:
          luaVersion: "5.4"
      - uses: hishamhm/gh-actions-luarocks@master  # See https://github.com/leafo/gh-actions-luarocks/pull/14
      - run: pacman -S mingw-w64-x86_64-dlfcn  # https://stackoverflow.com/a/77671742

      - name: Checkout srlua
        uses: actions/checkout@v4
        with:
          repository: LuaDist/srlua
          ref: dd0fc9461b4722d673631245d616e92c7c93c590
          path: srlua

      - name: Checkout pilot-compiler
        uses: actions/checkout@v4
        with:
          path: pilot-compiler

      - name: Build srlua
        run: |
          git apply ../pilot-compiler/srlua.patch
          make srlua.exe
        working-directory: srlua

      - run: |
          luarocks make
          ../srlua/glue ../srlua/srlua.exe pilot-compiler.lua pilot-compiler.exe
        working-directory: pilot-compiler

      - run: |
          ../pilot-compiler.exe main.lua
        working-directory: pilot-compiler/example
