on:
  push:
    branches: ["testing"]

jobs:
  build-exe:
    runs-on: windows-latest
    steps:
      # System depedencies
      - uses: ilammy/msvc-dev-cmd@v1
      - uses: leafo/gh-actions-lua@v10
        with:
          luaVersion: "5.1"
      - uses: hishamhm/gh-actions-luarocks@master  # See https://github.com/leafo/gh-actions-luarocks/pull/14

      - name: Checkout custom luapak branch
        uses: actions/checkout@v4
        with:
          repository: RiskoZoSlovenska/luapak
          ref: luarocks-3
          path: luapak

      - name: Install custom luapak
        run: luarocks make
        working-directory: luapak

      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: pilot-compiler

      - name: Test LFS
        run: |
          luarocks make
          lua pilot-compiler.lua
        working-directory: pilot-compiler

      - name: Bundle
        run: |
          luapak make --verbose
          tree
          dir dist
        working-directory: pilot-compiler

      - name: Test
        run: ../dist/pilot-compiler.exe main.lua
        working-directory: pilot-compiler/example

      - uses: actions/upload-artifact@v4
        with:
          path: pilot-compiler/dist/pilot-compiler.exe
