on:
  push:
    branches: ["testing"]

jobs:
  build-exe:
    runs-on: windows-latest
    steps:
      # System depedencies
      - uses: ilammy/msvc-dev-cmd@v1
      - uses: leafo/gh-actions-lua@v10
        with:
          luaVersion: "5.1"
      - uses: hishamhm/gh-actions-luarocks@master  # See https://github.com/leafo/gh-actions-luarocks/pull/14
        with:
          luaRocksVersion: "2.4"

      - name: Checkout pilot-compiler
        uses: actions/checkout@v4

      - name: Bundle
        run: |
          luarocks install luapak
          luapak make
          dir

      - name: Test pilot-compiler
        run: ../pilot-compiler.exe main.lua
        working-directory: example
