on:
  push:
    branches: ["testing"]

jobs:
  build-exe:
    runs-on: windows-latest
    steps:
      # System depedencies
      - uses: ilammy/msvc-dev-cmd@v1
      - uses: RiskoZoSlovenska/gh-actions-lua-static@static  # See https://github.com/lunarmodules/luasystem/pull/17#issuecomment-1986387525
        with:
          luaVersion: "5.2"
      - uses: luarocks/gh-actions-luarocks@master  # See https://github.com/leafo/gh-actions-luarocks/pull/14
        with:
          luaRocksVersion: "3.11.1"

      - run: tree ".lua" /f /a

      - name: Install amalg
        run: luarocks install amalg

      - name: Checkout Luastatic
        uses: actions/checkout@v4
        with:
          repository: lua-batteries/luastatic
          ref: f5da1fbbe5e1771ae6d6771e6258601cdfce75d8
          path: luastatic

      - name: Make luastatic
        run: luarocks make
        working-directory: luastatic

      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: pilot-compiler

      - name: Make
        run: luarocks make
        working-directory: pilot-compiler

      - name: Bundle
        run: |
          amalg.lua -x -s pilot-compiler.lua dkjson pl.path lfs -o out.lua
          luastatic out.lua `
            "${{ github.workspace }}/.lua/lib/lua52.lib" `
            -I"${{ github.workspace }}/.lua/include"
          move out.exe pilot-compiler.exe
        working-directory: pilot-compiler

      - run: tree /f /a
        working-directory: pilot-compiler

      - uses: actions/upload-artifact@v4
        with:
          path: pilot-compiler/pilot-compiler.exe

      - name: Test
        run: ../pilot-compiler.exe main.lua
        working-directory: pilot-compiler/example
